[phases.setup]
nixPkgs = [
  "...",

  # https://nixos.org/manual/nixpkgs/stable/#var-meta-priority
  '(lib.recursiveUpdate php83Packages.composer { meta.priority = php83Packages.composer.meta.priority or 0 -1; })',
]
