name: Tests

on: push

jobs:
  tdd:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test_db
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: php-actions/composer@v4
      - name: Generate Key
        run: php artisan key:generate
      - name: Run Tests
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        uses: php-actions/phpunit@v1

